apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devopscohorte2
spec:
  project: devops
  source:
    repoURL: 'https://github.com/mmkmou/test-argocd.git'
    path: main
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: production
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true