apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: transaction-main
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mmkmou/jenkins-k8s.git'
    path: main
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: production
  syncPolicy:
    syncOptions:
      - CreateNamespace=true