apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: transactions
  name: transactions
spec:
  replicas: 3
  selector:
    matchLabels:
      app: transactions
  template:
    metadata:
      labels:
        app: transactions
    spec:
      containers:
      - image: mmkmou/transactions
        name: transactions
        envFrom:
        - configMapRef:
            name: datasource
        
        
