apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: postgresql
  name: postgresql
spec:
  replicas: 1
  serviceName: "transactions-svc"
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:16.2
        name: db
        envFrom:
          - secretRef:
              name: db-password
        ports:
        - containerPort: 5432
        
        