apiVersion: v1
kind: Service
metadata:
  labels:
    app: transactions-svc
  name: transactions-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 31600
  selector:
    app: transactions
  type: LoadBalancer
